name: Go Install Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install gowitness at specific commit
        run: |
          apt-get update && apt-get install -y \
            ca-certificates chromium
          go install github.com/sensepost/gowitness@${GITHUB_SHA}

      - name: Verify Installation
        run: |
          gowitness scan single -u https://sensepost.com --write-jsonl

      - name: Generate a static report
        run: |
          gowitness report generate --json-file gowitness.jsonl
